// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVzJeMaiA0UkGn3vcs-jHb79qDQmIp_mw',
    appId: '1:274952164384:web:79309f859ad490e4c55845',
    messagingSenderId: '274952164384',
    projectId: 'prak-mobile-6e459',
    authDomain: 'prak-mobile-6e459.firebaseapp.com',
    storageBucket: 'prak-mobile-6e459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJQiJ3iPtaLpPH9wfksnTST5eTq1NjVM',
    appId: '1:274952164384:android:0bdd978e983ec577c55845',
    messagingSenderId: '274952164384',
    projectId: 'prak-mobile-6e459',
    storageBucket: 'prak-mobile-6e459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-MFMpH1i85NeU_bjgrtZ04v22bMwKUY',
    appId: '1:274952164384:ios:3fe578762d49dc53c55845',
    messagingSenderId: '274952164384',
    projectId: 'prak-mobile-6e459',
    storageBucket: 'prak-mobile-6e459.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-MFMpH1i85NeU_bjgrtZ04v22bMwKUY',
    appId: '1:274952164384:ios:3fe578762d49dc53c55845',
    messagingSenderId: '274952164384',
    projectId: 'prak-mobile-6e459',
    storageBucket: 'prak-mobile-6e459.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
